show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 2
show-holdings: true
currency: BRL
currency-summary-only: true
sort: alpha
watchlist:
      - CMIG4.SA
      - PETR4.SA
      - CSMG3.SA
      - NVDC34.SA
      - TSMC34.SA
      - VISA34.SA
      - MSCD34.SA
      - BTC/USD
